# Generated by Django 6.0.6 on 2026-07-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#7b809a', max_length=7)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=200)),
                ('wikipedia_query', models.CharField(blank=True, max_length=200)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especies', to='predios.grupo')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arboles', to='predios.especie')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arboles', to='predios.predio')),
            ],
            options={
                'verbose_name': 'Árbol',
                'verbose_name_plural': 'Árboles',
                'ordering': ['predio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('estado', models.CharField(choices=[('optima', 'Óptima'), ('buena', 'Buena'), ('regular', 'Regular'), ('critica', 'Crítica')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_salud', to='predios.arbol')),
            ],
            options={
                'verbose_name': 'Registro de Salud',
                'verbose_name_plural': 'Registros de Salud',
                'ordering': ['-fecha'],
            },
        ),
    ]
